function Allison3AntennaExposed = importfile2602allison3(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  ALLISON3ANTENNAEXPOSED = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the numeric data.
%
%  ALLISON3ANTENNAEXPOSED = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  ALLISON3ANTENNAEXPOSED = IMPORTFILE(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Allison3AntennaExposed = importfile2602allison3("C:\Users\Alessandro\Desktop\Polimi\Chicago Double Degree\5. Thesis\MyCode\MATLAB_20210215\File JSON\2021_02_26_Allison3_AntennaExposed.xlsx", "2021_02_26-Allison3", [1, 4407]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Mar-2021 10:56:00

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 4407];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":B" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.SelectedVariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Import the data
Allison3AntennaExposed = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":B" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Allison3AntennaExposed = [Allison3AntennaExposed; tb]; %#ok<AGROW>
end

%% Convert to output type
Allison3AntennaExposed = table2array(Allison3AntennaExposed);
end