function Me2trainingandafter = importfile0301_me(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  ME2TRAININGANDAFTER = IMPORTFILE1(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the numeric data.
%
%  ME2TRAININGANDAFTER = IMPORTFILE1(FILE, SHEET) reads from the
%  specified worksheet.
%
%  ME2TRAININGANDAFTER = IMPORTFILE1(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Me2trainingandafter = importfile0301_me("C:\Users\Alessandro\Desktop\Polimi\Chicago Double Degree\5. Thesis\MyCode\MATLAB_20210215\File JSON\2021_03_01-Me2_training_and after.xlsx", "2021_03_01-Me_training_and afte", [1010, 3511]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Mar-2021 16:59:30

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1010, 3511];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":B" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.SelectedVariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Import the data
Me2trainingandafter = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":B" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Me2trainingandafter = [Me2trainingandafter; tb]; %#ok<AGROW>
end

%% Convert to output type
Me2trainingandafter = table2array(Me2trainingandafter);
end