function Me1NitrileNose = importfile0304_me1_nit_nose(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  ME1NITRILENOSE = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the
%  numeric data.
%
%  ME1NITRILENOSE = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  ME1NITRILENOSE = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Me1NitrileNose = importfile0304_me1_nit_nose("C:\Users\Alessandro\Desktop\Polimi\Chicago Double Degree\5. Thesis\MyCode\MATLAB_20210215\File JSON\2021_03_04-Me1_Nitrile_Nose.xlsx", "2021_03_04-Me1_Nitrile_Nose", [2, 4006]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Mar-2021 14:51:04

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 4006];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":B" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.SelectedVariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Import the data
Me1NitrileNose = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":B" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Me1NitrileNose = [Me1NitrileNose; tb]; %#ok<AGROW>
end

%% Convert to output type
Me1NitrileNose = table2array(Me1NitrileNose);
end