function calInMouthtapeallcovered = importfile0219b(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  CALINMOUTHTAPEALLCOVERED = IMPORTFILE1(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the numeric data.
%
%  CALINMOUTHTAPEALLCOVERED = IMPORTFILE1(FILE, SHEET) reads from the
%  specified worksheet.
%
%  CALINMOUTHTAPEALLCOVERED = IMPORTFILE1(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  calInMouthtapeallcovered = importfile0219b("C:\Users\Alessandro\Desktop\Polimi\Chicago Double Degree\5. Thesis\MyCode\MATLAB_20210215\File JSON\2021_02_19-02_calInMouth_tape_allcovered.xlsx", "2021_02_19-02_calInMouth_tape_a", [1, 5044]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Feb-2021 11:30:54

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 5044];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":B" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.SelectedVariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Import the data
calInMouthtapeallcovered = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":B" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    calInMouthtapeallcovered = [calInMouthtapeallcovered; tb]; %#ok<AGROW>
end

%% Convert to output type
calInMouthtapeallcovered = table2array(calInMouthtapeallcovered);
end