function exposednotinMouth = importfile0221b(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  EXPOSEDNOTINMOUTH = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the numeric data.
%
%  EXPOSEDNOTINMOUTH = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  EXPOSEDNOTINMOUTH = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  exposednotinMouth = importfile("C:\Users\Alessandro\Desktop\Polimi\Chicago Double Degree\5. Thesis\MyCode\MATLAB_20210215\File JSON\2021_02_21-02_exposed_notinMouth.xlsx", "2021_02_21-02_exposed_notinMout", [2, 2436]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Feb-2021 12:40:35

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 2436];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":B" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.SelectedVariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Setup rules for import
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts = setvaropts(opts, [1, 2], "TreatAsMissing", '');

% Import the data
exposednotinMouth = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":B" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    exposednotinMouth = [exposednotinMouth; tb]; %#ok<AGROW>
end

%% Convert to output type
exposednotinMouth = table2array(exposednotinMouth);
end